### ISSUE TITLE
timestamp empty using Regen API

### ISSUE THREAD

**Issue by amaury1729** [regen-network/regen-js#17]
Querying this tx:
http://13.59.81.92:26657/tx?hash=0xC7F4DDC696BB64605D2ACB45D5999CF3E36F2F73783E6DB5066CFB282A6E7C42

- Using the CLI: the timestamp is not empty
- Using RegenApi: the timestamp is empty

**Comment by ryanchristo** [comment]
As far as I can tell this has been resolved.
