### ISSUE TITLE
update cosmJS

### ISSUE THREAD

**Issue by gotjoshua** [regen-network/regen-js#21]
currently this repo is still referencing 

"@cosmjs/stargate": "^0.24.0-alpha.17"

latest is

"@cosmjs/stargate": "^0.26.5"

**Comment by blushi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/regen-js/21?planning-poker) with ZenHub @mhagel @victordelval

**Comment by mhagel** [comment]
`yarn link` to test against regen-web

**Comment by blushi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/regen-js/21?planning-poker) with ZenHub @haveanicedavid

**Comment by mhagel** [comment]
Once this is merged, I will create a `regen-web` PR to use the latest changes from regen-js
