### ISSUE TITLE
Set up Buf Generate

### ISSUE THREAD

**Issue by haveanicedavid** [regen-network/regen-js#29]
In `regen-js`, set up the buf generate with `ts-proto` + buf schema registry https://buf.build/regen/regen-ledger/ (we should also make sure we add all current proto files there, see https://github.com/regen-network/regen-ledger/tree/master/proto/regen)

There's an existing buf plugin for ts-proto https://github.com/stephenh/ts-proto/pull/573/ but since we're actually using a fork of ts-proto https://github.com/regen-network/ts-proto https://www.npmjs.com/package/@regen-network/ts-proto, we need to create our own plugin

Useful resources:
- https://docs.buf.build/bsr/remote-generation/js
- https://docs.buf.build/configuration/v1/buf-gen-yaml

**Comment by haveanicedavid** [comment]
@mhagel

**Comment by blushi** [comment]
@haveanicedavid @flagrede @mhagel @victordelval 
Something to tackle pretty soon. Indeed in the `protocgen.sh` script, we use `buf protoc`, which has been removed as part of https://github.com/bufbuild/buf/releases/tag/v1.0.0 (see changelog there) so for the code generation to work, you'll need to use a version of buf prior to v1.0.0 for now, until we set up buf yaml files. Please ping @amaurym or @aaronc if you need any support on that when I'm on maternity leave.

**Comment by S4mmyb** [comment]
Thanks for flagging this @blushi !
