### ISSUE TITLE
Add Amino signing support to regen-ledger msgs

### ISSUE THREAD

**Issue by blushi** [regen-network/regen-js#35]
The current version of @regen-network/api doesn't support amino signing for transactions with regen-ledger msgs. It should be added so that we can sign such transactions through a ledger hardware wallet for instance which only supports legacy amino sign mode for now.

For example, if you try to do so, you'll get this type of error:

> Type URL '/regen.ecocredit.v1alpha1.MsgRetire' does not exist in the Amino message type register. If you need support for this message type, you can pass in additional entries to the AminoTypes constructor. If you think this message type should be included by default, please open an issue at https://github.com/cosmos/cosmjs/issues.

For regen-ledger msgs (we could start with the ones from the ecocredit module for now since those are the only ones we're really using in https://github.com/regen-network/regen-web/tree/master/web-registry), we need to add amino converters, like it's done for instance for bank on cosmjs: https://github.com/cosmos/cosmjs/blob/fe34588ff12756d0453c94e792a781f8ecc72315/packages/stargate/src/modules/bank/aminomessages.ts
In particular for the ecocredit v1alpha1 (regen-ledger v3.0), the aminoType's can be found in:
- https://github.com/regen-network/regen-ledger/blob/v3.0.0/x/ecocredit/codec.go#L12-L18
- https://github.com/regen-network/regen-ledger/blob/v3.0.0/x/ecocredit/basket/codec.go#L13-L17

As part of regen-ledger v4.0, new versions of existing msgs with different amino type names and new msgs have been added, e.g.:
- https://github.com/regen-network/regen-ledger/blob/d5b276015189d335cce7830ead520fdca3df7f5e/x/ecocredit/core/codec.go#L15-L30
- https://github.com/regen-network/regen-ledger/blob/d5b276015189d335cce7830ead520fdca3df7f5e/x/ecocredit/basket/codec.go#L13-L17

We should primarily focus on those now.

Lastly, once those amino converters are set up, we can use them to instantiate the stargate signing client (`createStargateSigningClient` in `/packages/api/src/tx/msgs.ts`) by passing aminoTypes as part of [`SigningStargateClientOptions` ](https://github.com/cosmos/cosmjs/blob/b63075aca18538a0c9f312dfaf43be271f5d39aa/packages/stargate/src/signingstargateclient.ts#L89)

A new version of @regen-network/api should be tagged and published on npm once that's done.

**Comment by blushi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/regen-js/35?planning-poker) with ZenHub @flagrede @haveanicedavid @mhagel @victordelval

**Comment by wgwz** [comment]
@blushi would you be open to some pair programming on this one? i would like to understand this problem better and be able to contribute on these types of issues.

**Comment by blushi** [comment]
> @blushi would you be open to some pair programming on this one? i would like to understand this problem better and be able to contribute on these types of issues.

Sure let's discuss that during our 1-1 today.

**Comment by mhagel** [comment]
@wgwz I am happy to team up on this with you, since I have a device to test with

**Comment by mhagel** [comment]
check out telescope from osmosis
