### ISSUE TITLE
Add amino types to amino map

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-js#70]
Ref: https://github.com/regen-network/regen-js/pull/68#discussion_r1194139712

We need to add amino types to the amino map in `packages/api/scripts/aminos.js`. This will enable amino signing.

```
export const AMINO_MAP = {
  // TODO: add amino types
  // '/ibc.applications.transfer.v1.MsgTransfer': {
  //   aminoType: 'cosmos-sdk/MsgTransfer'
  // }
};
```

**Comment by blushi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/regen-js/70?planning-poker) with Zenhub @ryanchristo

**Comment by ryanchristo** [comment]
Cross-referencing my comment in the groups-ui repository: https://github.com/regen-network/groups-ui/issues/10#issuecomment-1568844358

Looks like this is a known issue and may have been resolved...

https://github.com/osmosis-labs/telescope/issues/281
